notifications:
  email: false

matrix:
  include:
  - sudo: required
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
    language: python
    python: "2.7"
  - sudo: required
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686 PRE_CMD=linux32
    language: python
    python: "2.7"
  - os: osx
    osx_image: xcode6.4
    env: HOMEBREW_NO_AUTO_UPDATE=1

install:
- if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then docker pull $DOCKER_IMAGE; fi
# On macOS we need to build with GCC, because CLang is somehow much slower
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python gcc; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip install --upgrade wheel setuptools; fi

script:
- mkdir wheelhouse
- if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis/build-wheels.sh; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then env CC=gcc-6 python setup.py bdist_wheel --dist-dir wheelhouse; fi
- ls -al wheelhouse/
- pip install twine
- twine upload --skip-existing -u Safihre -p $pypassword wheelhouse/*
