notifications:
  email: false

matrix:
  include:
  - os: linux
    language: python
    python: "3.5"
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
  - os: linux
    language: python
    python: "3.6"
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
  - os: linux
    language: python
    dist: "xenial"
    python: "3.7"
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
  - os: osx
    env: HOMEBREW_NO_AUTO_UPDATE=1

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew install python gcc;
    fi;
  - python3 --version
  - python3 -m pip install --upgrade -r tests/requirements.txt

script:
  - mkdir wheelhouse
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      python3 setup.py install;
      python3 setup.py bdist_wheel --dist-dir wheelhouse;
    else
      python3 setup.py install;

    fi;
  - ls -al wheelhouse/
  - python3 -m pytest
  - python3 -m pip install twine
  - #docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis/build-wheels.sh;
  #- twine upload --skip-existing -u Safihre -p $pypassword wheelhouse/*
