notifications:
  email: false

matrix:
  include:
  - sudo: required
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
  - sudo: required
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686 PRE_CMD=linux32

install:
- docker pull $DOCKER_IMAGE

script:
- ls -al
- mkdir wheelhouse
- docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis/build-wheels.sh
- ls -al wheelhouse/
- pip install --upgrade pip
- pip install twine
- twine upload --skip-existing -u Safihre -p $pypassword wheelhouse/*
