environment:
  pypassword:
    secure: fYF+6TvQdqbg7u+c+NraAg==

  matrix:
    # For Python versions available on Appveyor, see
    # http://www.appveyor.com/docs/installed-software#python
    # The list here is complete (excluding Python 2.6, which
    # isn't covered by this document) at the time of writing.
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python37"
    - PYTHON: "C:\\Python37-x64"

install:
  # We need wheel installed to build wheels
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - python --version
  - pip install --upgrade -r tests/requirements.txt
  - pip install --upgrade setuptools wheel twine

build_script:
  - python setup.py install

test_script:
  # First we test before we build the rest
  - python -m pytest

after_test:
  # Passed! Now let's deploy
  - python setup.py bdist_wheel --dist-dir wheelhouse
  - python setup.py sdist --dist-dir wheelhouse
  - python.exe -m twine upload --skip-existing -u Safihre -p %pypassword% wheelhouse/*
